name: Sync Fork and Update Branches

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - master # Trigger on pushes to the master branch

jobs:
  sync-fork:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository
      - name: Checkout Fork
        uses: actions/checkout@v4
        with:
          persist-credentials: false # Disable default GitHub token
          fetch-depth: 0 # Fetch all history for all branches

      # Step 2: Add the upstream repository
      - name: Add Upstream
        run: |
          git remote add upstream https://github.com/pegasystems/pega-helm-charts.git
          git fetch upstream

      # Step 3: Sync master with upstream/master
      - name: Sync Master
        run: |
          git checkout origin/master
          git merge upstream/master
          git push origin master --force-with-lease

      # Step 4: Update Feature Branches
      - name: Update Feature Branches
        run: |
          for branch in $(git branch --list | grep -v master); do
            git checkout origin/$branch
            git merge origin/master
            git push origin $branch --force-with-lease
          done